### ISSUE TITLE
feat: see comparisons when test passed

### ISSUE THREAD

**Issue by emmanuelgeoffray** [FRSOURCE/cypress-plugin-visual-regression-diff#104]
I'm always frustrated when I have a passed test that I can't see the diff.
I often have tests with a threshold of 1000, allowing some minor rendering difference.

I'd like to visually double check the diff with the same tool used when clicking "See comparaisons" when a test is failing.

**Comment by FRSgit** [comment]
Hey, can I get more information about your use case?
Why do you have test cases with such high threshold? Isn't it against the sole purpose of visual regression tests? Can you elaborate about it a bit more?

About feature request - it seems like something doable, though I probably wouldn't enable it by default - it should be toggable via configuration option. What do you think?

**Comment by emmanuelgeoffray** [comment]
I am testing style renderings on a canvas and I've noticed fonts can be a bit blurred on some device.
This threshold does not seems so high on a 500x500 rendering size and allows to pass the test.

Sure, it could be a toggable option but it could also be there by default as I don't think it adds visual pollution :
user stills has to click the test to see details and the "See comparaisons" link.
And it is always nice and satisfying to check that a test passes and confirm that the old image is the same as the new image.

**Comment by FRSgit** [comment]
@emmanuelgeoffray Sorry for the late response - I've prioritised other issues a bit higher and needed to handle them first.

> Sure, it could be a toggable option but it could also be there by default as I don't think it adds visual pollution :
user stills has to click the test to see details and the "See comparaisons" link.

It's not only visual pollution - currently the plugin doesn't save comparison files to the hard drive if the test passes. This feature would pollute the users' hard drive much more.

Either way - I think it can be done fairly easy. the `writeFileSync` in the `src/plugins.ts` line 174 should be moved upwards & nested within condition that would check whether correct flag/option was passed in or not.

I'm just wondering how should it work with `updateImages` option. It's a config option that forces all image to be updated, it's useful to prepare CI actions that replace all of the screenshots with the "newest ones" automatically.
I think in such case the functionality of saving old files & file diffs shouldn't be available. When `updateImages` is turned on the image diff is not even triggered. No need to complicate this part of the codebase.

**Comment by FRSgit** [comment]
@emmanuelgeoffray Good news - I've figured that I can display images without the need to store them on hard drive!

Added the feature to see image comparison for successful tests as a part of PR #137 - it's been released in [version 2.3.0](https://www.npmjs.com/package/@frsource/cypress-plugin-visual-regression-diff/v/2.3.0) 🚀 
I think that should handle your use-case - please, give it a try! 🙏 

Of course - if you find any error - create a new bug issue. 😁

**Comment by emmanuelgeoffray** [comment]
Thank you for your response :)

Your description of the feature looks totally OK to me !
I agree it should not mess with the `updateImages` option.

Le dim. 11 sept. 2022 à 23:31, Jakub Freisler ***@***.***> a
écrit :

**Comment by emmanuelgeoffray** [comment]
it's great !
thank you :+1:
