### ISSUE TITLE
Calculation of image difference percentage is incorrect

### ISSUE THREAD

**Issue by NathanielAvery** [FRSOURCE/cypress-plugin-visual-regression-diff#107]
Hi 👋🏻 Thanks for writing this plugin!

**Describe the bug**

When the plugin determines the percentage of changed pixels, its calculation is incorrect:
https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/blob/b4c6617e5ff817ffd0290c36fcfab1517e67c964/src/plugins.ts#L164

As `pixelmatch` returns the number of different pixels, this line should be:
```TypeScript
imgDiff = diffPixels / (width * height); 
```

**To Reproduce**

- Create an empty 100x100 `<div>` element
- Capture a snapshot of that element in a Cypress test with a threshold of `0.5`.
- Modify the snapshot image so that just below 50% of the pixels are different.
- Re-run the test.
- Expected behavior: Test passes. 
- Actual behavior: Test fails.

**Comment by FRSgit** [comment]
Hi @NathanielAvery,

🤦 You're absolutely right. Thanks for the good catch!

**Comment by FRSgit** [comment]
Fixed in 529cb22a22200af234bdbc1399b6f97880001d12
