### ISSUE TITLE
Support "autoCleanUp" like cypress-plugin-snapshots does

### ISSUE THREAD

**Issue by iamyoki** [FRSOURCE/cypress-plugin-visual-regression-diff#118]
**Is your feature request related to a problem? Please describe.**
Auto clean up untested image files can be useful to remain minimum file storage when we changed the matchImage title of test

**Describe the solution you'd like**
Automatically remove snapshots that are not used by test

**Comment by FRSgit** [comment]
Hi @iamyoki!

That's and interesting feature request, I'll look into that!
My only concern is how this feature should work in situation then some of the test cases (`it()`) are skipped. We probably can handle that by just notifying users in the docs that their screenshots will be removed if `autoCleanUp` is enabled and the test case is skipped. WDYT?

**Comment by FRSgit** [comment]
Hey @iamyoki !
I've just created new PR resolving this issue: #124. I've published it to npm under [`3.0.0-alpha.0`](https://www.npmjs.com/package/@frsource/cypress-plugin-visual-regression-diff/v/3.0.0-alpha.0), can you give it a try please? 🙏

**Comment by FRSgit** [comment]
@iamyoki Kind reminder - would you like to check if PR #124 is what you had in mind with this feature request please?
