### ISSUE TITLE
It does not compare the screenshots but takes them as new images

### ISSUE THREAD

**Issue by Skillonaut** [FRSOURCE/cypress-plugin-visual-regression-diff#133]
Hello, I have a problem and it doesn't matter how different the new screenshot is from the old one it always says "Image diff factor (0%) is within boundaries of maximum threshold option 0.01. "even if they are 2 completely different images. 

I have tried several things to solve the problem but nothing seems to work. Whether to use a "updateImages: false" or so that the right image is found a "title:" in the config made no difference at all.

**Comment by FRSgit** [comment]
Hey @Skillonaut!

Sorry for delayed response.
Can you please provide more details about your project? What is your cypress version, config, project/test structure?

How did you provide "different images" to cypress so it should fail?

I just tried out the example sitting in the [`example`](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/tree/main/example) directory and it seems to work properly - it was succeeding with "old image", but when I've changed content of one of the vue components it has failed. Can you try it out by yourself and see if you can reproduce the issue there?

**Comment by FRSgit** [comment]
Due to no response I'm going to close this issue as stale. Please file new issue when the issue occurs and you'll be willing to to provide the reproduction steps.
Have a great day!
