### ISSUE TITLE
Update CyPress 9.7.0 to 10.X

### ISSUE THREAD

**Issue by mmartinsdev** [FRSOURCE/cypress-plugin-visual-regression-diff#136]
**Describe the bug**
Hi, since i have updated my project to CyPress 10 and the plugin image comparaison, I have this errors : 

** matchImage() is not a function.. **

I have follow the procedure to migrate CyPRess and plugin compare image. 

Can you help me ? 

Thanks

**Comment by FRSgit** [comment]
Hey @mmartinsdev,

Can you please give more details about your project? I need to reproduce the problem. What is your cypress configuration, project structure, do you get any type of error notification anywhere (in the console or within Cypress UI)?

Current version of plugin is tested against Cypress 10, also, look for "Cypress 10" instructions in our [installation guide](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff#installation).

**Comment by FRSgit** [comment]
Due to no response I'm going to close this issue as stale. If the problems occurs again please file a new issue with reproduction steps provided.
Have a great day!
