### ISSUE TITLE
Missing npm package types

### ISSUE THREAD

**Issue by bwswedberg** [FRSOURCE/cypress-plugin-visual-regression-diff#167]
**Describe the bug**

The types (dist/*.d.ts) aren't packaged with the npm repo which prevents typescript projects from inferring types.

**To Reproduce**
1. Create a typescript cypress project
2. `npm install --save-dev @frsource/cypress-plugin-visual-regression-diff`
3. Begin `@frsource/cypress-plugin-visual-regression-diff` install steps: 
```typescript
import '@frsource/cypress-plugin-visual-regression-diff'; // warning shown here
```
> Could not find a declaration file for module '@frsource/cypress-plugin-visual-regression-diff'. '/Users/.../node_modules/@frsource/cypress-plugin-visual-regression-diff/dist/support.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/frsource__cypress-plugin-visual-regression-diff` if it exists or add a new declaration (.d.ts) file containing `declare module '@frsource/cypress-plugin-visual-regression-diff';`ts(7016)

**Expected behavior**

Types to be included in npm package since this is a typescript repo. It looks like they previously were based on the package.json.

![image](https://user-images.githubusercontent.com/7384136/199205014-47cb91f1-fb84-4ecb-a693-0648c22d1b6f.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/7384136/199203672-832e009a-de67-480d-a059-bb02d7ba2a3c.png)

**Please complete the following information:**
 - OS and version: [e.g. Windows 10 build. 19043.1319] MacOS 12.4
 - Browser and version [e.g. chrome 22] N/A
 - Cypress version [e.g. 8.6.0] 10.11.0
 - @frsource/cypress-plugin-visual-regression-diff version 3.0.2

**Additional context**

**Comment by FRSgit** [comment]
Hello @bwswedberg, thanks for such detailed bug report, it's really hearth-warming to see those 😄 
You're right, the typings were in the package at some point, so it's a regression. Sorry for my mistake - I've introduced an issue by doing an upgrade of microbundle recently.

I've just released version [3.0.3](https://www.npmjs.com/package/@frsource/cypress-plugin-visual-regression-diff/v/3.0.3) with a fix, enjoy! 🎉  (and please - confirm here that it works 😄 )

**Comment by FRSgit** [comment]
There are two things there:

#### 1. Adressing the missing typings issue:
According to the typescript repo, you must set moduleResolution to `node16` in your `tsconfig.json` to make it working with modern `exports` fields ([see here](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1270460323)).

But I've found [a solution on how to support "older typescript configuration".](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/pull/170/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R36-R48). This got release under version 3.0.4 (also, have a look at [updated example](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/tree/main/example) in this repo).

#### 2. Addressing the issue where you need to still use `@frsource/cypress-plugin-visual-regression-diff/dist/support` syntax when bundling your app with webpack.

There is an issue of Cypress - under the hood, the webpack processor used by Cypress internally for webpack builds is using outdated webpack version 4. This means - no proper support for `exports` syntax in `package.json` (which is the modern node syntax for expressing package exports).

This issue cannot be handled before Cypress upgrades webpack to v5 - then the problem should go away by itself. Issue that tracks webpack 5 upgrade is [here](https://github.com/cypress-io/cypress/issues/19555).

**Comment by bwswedberg** [comment]
I upgraded to `3.1.0`, and those type related issues have been resolved.

Thanks again!!
