### ISSUE TITLE
Write diff file to directory provided as config option

### ISSUE THREAD

**Issue by jestapinski** [FRSOURCE/cypress-plugin-visual-regression-diff#211]
👋 

I'd like the option to write output actual/diff files to Cypress's screenshots folder (instead of (or in addition to) the __image_snapshots__) dir. This is because our CI uploads images from this directory (would be high level of effort to dynamically search directories near our tests).

**Comment by FRSgit** [comment]
This can be already specified via `imagesPath` option. Have a look at our docs: https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/blob/main/README.md#:~:text=default%3A%20%27%7Bspec_path%7D/__image_snapshots__%27-,imagesPath,-%3A%20%27this%2Dmight

**Comment by jestapinski** [comment]
Ah, slightly different ask

I want the baseline images stored in a separate place from the diff/actual. Is that possible or are all of them expected to be in the same directory? [Seems like they all currently go to whatever `imagesPath` might be](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/blob/main/src/commands.ts#L231-L233)
