### ISSUE TITLE
maxDiffThreshold doesn't allow 0

### ISSUE THREAD

**Issue by OriR** [FRSOURCE/cypress-plugin-visual-regression-diff#213]
**Describe the bug**
`maxDiffThreshold` is a number that represents the maximum fractional value of pixels changed, where 1 means all pixels are different and 0 means all pixels are the same.

However, when setting it to 0, it fallbacks to 0.01.

**To Reproduce**
Set maxDiffThreshold to 0, create a test that matches the snapshots and run it, then change a single character and see that the test still passes.

**Expected behavior**
The above test should fail.

**Additional context**
It appears to be because the default value is set using `||` and not using `??` which makes 0 a falsy value and thus fallbacks to 0.01.

**Comment by FRSgit** [comment]
Hey, this got fixed in commit f4d3ec946547d648d1ec8ea9ccf9369540255adf and got release under `v3.2.11`
