### ISSUE TITLE
`imagesPath` is not valid attribute

### ISSUE THREAD

**Issue by mgubala-edge1s** [FRSOURCE/cypress-plugin-visual-regression-diff#220]
**Describe the bug**
Readme states that `imagesPath` is attribute which can be used to adjust storage path. It is not valid as in code there is `imagesDir`.

**To Reproduce**

1. Try using `matchImage({ imagesPath: 'some-path/ })` and it will not do any change.
2. Try using `matchImage({ imagesDir: 'some-path/ })` and it will change where images are stored.

**Expected behavior**
Readme should match codebase.

**Comment by FRSgit** [comment]
What version do you use? Currently in the codebase both `imageDir` and `imagePath` are supported. Also, `imageDir` is marked as deprecated and will be removed in version 4.

One note: to be able to use `imagePath` you cannot use `imageDir` anywhere in your environment.

**Comment by FRSgit** [comment]
Code where `imagesPath` is being used:
https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/blob/f4d3ec946547d648d1ec8ea9ccf9369540255adf/src/commands.ts#L96-L99
https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/blob/f4d3ec946547d648d1ec8ea9ccf9369540255adf/src/commands.ts#L151

**Comment by FRSgit** [comment]
Closing as invalid
