### ISSUE TITLE
TypeError cy.get(...).matchImage is not a function

### ISSUE THREAD

**Issue by ruimarques-lseg** [FRSOURCE/cypress-plugin-visual-regression-diff#238]
### Describe the Bug

With cypress@12.13.0

Setting up the plugin in Typescript as described in the README results in the following error:

`TypeError cy.get(...).matchImage is not a function`

Unlike the README, the [example app](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/blob/main/example) seems to be correct so following it fixes the issue.

Solution:

It can be solved by adding this to `commands.ts`:

`import '@frsource/cypress-plugin-visual-regression-diff/dist/support';`

Then this can removed from `support/index.ts` as it doesn't seem to be needed:

`import '@frsource/cypress-plugin-visual-regression-diff';`

### Expected behavior

No error thrown.

### Package version

3.3.5

### Device

Macbook

### OS and version

OSx

### Browser and version

chrome 113

### Node version

16.18.0

### I can work on it by myself

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FRSgit** [comment]
Hey @ruimarques-lseg!

Thanks for filing an issue!

Can you share more details about your environment?
What bundler do you use (and in which version)?
Do you use typescript?

I think the whole issue is connected with whether you use a bundler that read `exports` section of package.json correctly or not - our example is currently based on vue-cli (so it runs on the old webpack version). That is why it needs an explicit declaration when importing the plugin. Maybe adding information about this to the docs will be enough?

What are your thoughts here?

**Comment by FRSgit** [comment]
Hey,

I'm closing this ticket as stale. Please open a new issue if you think the bug is still present and please provide more details + reproduction scenario.

Have a great week!
