### ISSUE TITLE
[Bug]: Readme not up to date

### ISSUE THREAD

**Issue by FrederikG** [FRSOURCE/cypress-plugin-visual-regression-diff#293]
### Describe the Bug

In the examples, the command `matchImage` is added in the `commands.ts` file https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/blob/main/examples/webpack/cypress/support/commands.ts. But this step is missing in the official Readme: https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff

If you just follow the steps in the Readme, cypress will throw an error, that `matchImage` is not a function.

### Expected behavior

The Installation steps in the readme also mentions the adding of the command in the `command.ts`.

### Package version

3.3.10

### Device

PC

### OS and version

Windows 11

### Browser and version

Chrome

### Node version

16.0

### I can work on it by myself

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FRSgit** [comment]
Hey @FrederikG!

Thanks for raising this issue. However, if you follow official documentation you'll end up with `import "@frsource/cypress-plugin-visual-regression-diff";` in `cypress/support/index.js` and that should be enough as `/support` is [a default entry point of this package](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/blob/main/packages/cypress-plugin-visual-regression-diff/package.json#L11-L17).

I'm closing the issue as I think everything works as expected - if you believe that it does not or should work differently: please reopen this issue or raise the PR with changes, thanks!
