### ISSUE TITLE
Option to override title

### ISSUE THREAD

**Issue by dhulme** [FRSOURCE/cypress-plugin-visual-regression-diff#79]
Hi, we want to be able to override the title used in the screenshot name. This is because we capture screenshots in different browsers and so want to have the display name of the browser into the screenshot file name. 

Perhaps `title` could be loaded from the options object if it defined?

I tried manually appending `Cypress.currentTest.titlePath`, but this doesn't seem to persist inside the plugin.

Thank you

**Comment by FRSgit** [comment]
Hey @dhulme!

It's a valid feature request - I think the plugin's API could be expanded a bit to allow setting `title` by passing correct option to `matchImage` command call. Would you like to give it a try by making a PR? I might not have time to start working on this one this week 😞 

For now, you could also use `imagesDir` option and store screenshots from different browsers within separate directories.

BTW: `Cypress.currentTest.titlePath` probably won't work as it's set by Cypress itself based on [the test name.](https://docs.cypress.io/api/cypress-api/currenttest#Get-current-test-title)

**Comment by dhulme** [comment]
Sure, no problem. We're migrating from another screenshot plugin so want to keep our current screenshot folder structure. I have opened a PR: https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/pull/81

**Comment by FRSgit** [comment]
Thanks for the PR!
Out of curiosity - what made you migrate from previous screenshot plugin to this one?

**Comment by dhulme** [comment]
No problem 😀 It didn't support Cypress 10, the project wasn't maintained and had got more buggy over time! 😥

**Comment by FRSgit** [comment]
Glad that this library is useful for you! Closing the issue as it's fixed - thanks for collaboration 🚀
