### ISSUE TITLE
Fails with TypeError: fs__default.default.rm is not a function

### ISSUE THREAD

**Issue by stephenwil** [FRSOURCE/cypress-plugin-visual-regression-diff#89]
**Describe the bug**
Fails with TypeError:
**TypeError: fs__default.default.rm is not a function**
after taking screenshot in Cypress 10.3.1. Mix up of ESM & CJS?

**To Reproduce**
1. Using Cypress 10.3.1 & cypress-cucumber
2. Cypress commands.ts file has 
```
import '@frsource/cypress-plugin-visual-regression-diff/dist/support';
```
&
Cypress config file has
import { initPlugin } from '@frsource/cypress-plugin-visual-regression-diff/dist/plugins';

```
const setupNodeEvents = async (on, config) => {
  await addCucumberPreprocessorPlugin(on, config);
  initPlugin(on, config);
}
```
4. Have a step definition that calls cy.matchImage()
5. Screenshots have been taken in 2 places
- 
7. See error

```
index.1d817fa5.js:96604 TypeError: fs__default.default.rm is not a function
    at /node_modules/@frsource/cypress-plugin-visual-regression-diff/src/plugins.ts:225:14
From previous event:
    at $Cypress.automation (http://localhost:9000/__cypress/runner/cypress_runner.js:168497:12)
    at automate (http://localhost:9000/__cypress/runner/cypress_runner.js:158918:20)
    at automateScreenshot (http://localhost:9000/__cypress/runner/cypress_runner.js:158928:10)
    at scrollAndTake (http://localhost:9000/__cypress/runner/cypress_runner.js:159006:12)
From previous event:
    at takeScrollingScreenshots (http://localhost:9000/__cypress/runner/cypress_runner.js:159009:58)
    at takeFullPageScreenshot (http://localhost:9000/__cypress/runner/cypress_runner.js:159043:10)
    at http://localhost:9000/__cypress/runner/cypress_runner.js:159281:14
From previous event:
    at takeScreenshot (http://localhost:9000/__cypress/runner/cypress_runner.js:159269:29)
    at Context.screenshot (http://localhost:9000/__cypress/runner/cypress_runner.js:159389:14)
    at Context.<anonymous> (http://localhost:9000/__cypress/runner/cypress_runner.js:171965:19)
    at http://localhost:9000/__cypress/runner/cypress_runner.js:170643:15
From previous event:
    at CommandQueue.runCommand (http://localhost:9000/__cypress/runner/cypress_runner.js:170622:17)
    at next (http://localhost:9000/__cypress/runner/cypress_runner.js:170774:19)
    at http://localhost:9000/__cypress/runner/cypress_runner.js:170803:16
```

An empty folder has been created in:
cypress/screenshots/__cp-visual-regression-diff_snapshots__/cypress/e2e/visual-testing/.../__image_snapshots__
And an image has been placed at:
cypress/e2e/visual-testing/.../__image_snapshots__/YYYY.actual.png

**Expected behavior**
No error to occur, and not 2 directories to be used?

**Screenshots**
<img width="716" alt="Screenshot 2022-08-18 at 10 11 04" src="https://user-images.githubusercontent.com/1395944/185360664-ad0cb039-a616-435d-ae43-9383867eb14f.png">

**Please complete the following information:**
 - OS and version: MacOS Big Sur 11.6.4
 - Browser and version Electron v100
 - Cypress version 10.3.1

**Additional context**

**Comment by FRSgit** [comment]
Hello @stephenwil!

Can you please write down what version of Node.js are you running your cypress tests on?

**Comment by FRSgit** [comment]
It seems that your case works same way as an [example that's set up in this repo](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/tree/main/example). Please confirm @stephenwil.

I've just checked the example against Node 16.16 on MacOS Monterey 12.4 on both Electron and Chrome - it seems that everything works okay.

I need more info to reproduce this issue, can you assist me with that please (you could start with sending me your Node version)?

**Comment by FRSgit** [comment]
Hey @stephenwil - have you got any updates about this issue?

As I'm not able to reproduce for a week now I've marked this issue with a "stale" label. If nothing happens in this thread for next week I'll need to close it

**Comment by FRSgit** [comment]
Due to no response and no luck with reproduction of the issue in an environment containing cucumber plugin - I'm closing this issue.
Feel free to open a new issue if you believe the issue still exists.
